version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    networks:
      default:
    ports: 
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    volumes:
     - "./conf.d:/etc/mysql/conf.d"
  apps:
    container_name: app-pet
    build: .
    depends_on:
      - mysql     
    restart: always
    networks:
       default:
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/petclinic
      SPRING_DATASOURCE_INITIALIZATION-MODE: always
    ports:
      - 80:8080

networks:
  default:

     
     